
name = "FefferyUtilsComponents"
uuid = "1b08a953-4be3-4667-9a23-ea89cd6d0d23"
authors = ["CNFeffery <fefferypzy@gmail.com>"]
version = "0.2.0-rc6"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
